# Generated by Django 3.2 on 2021-04-10 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_terrauser_email"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="terrauser",
            name="username",
        ),
    ]
