# Generated by Django 3.2 on 2021-04-10 19:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_terrauser_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsersStates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_prefix', models.CharField(max_length=10, unique=True, verbose_name='Префикс ссылки на Terra GUI')),
                ('port', models.IntegerField(unique=True, verbose_name='Индивидуальный порт соединения')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
