# Generated by Django 3.2 on 2021-04-11 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_usersstates"),
    ]

    operations = [
        migrations.AddField(
            model_name="terrauser",
            name="user_token",
            field=models.CharField(
                default=1, max_length=30, verbose_name="токен авторизации"
            ),
            preserve_default=False,
        ),
    ]
