# Generated by Django 3.2 on 2021-04-12 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_terrauser_user_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="terrauser",
            name="user_token",
            field=models.CharField(
                max_length=30, unique=True, verbose_name="токен авторизации"
            ),
        ),
    ]
